export const portfolioTextCard = [
  {
    name: "MERLIN 5TH AVENUE",
    location: "MAHISBATHAN",
    tr: "2200HP VRV",
    type: "RESIDENTIAL",
    id: "merlin-5",
  },
  {
    name: "AVIDIPTA PHASE-II",
    location: "MUKUNDAPUR",
    tr: "1000HP VRV",
    type: "RESIDENTIAL",
    id: "avidipta-p2",
  },
  {
    name: "ORBIT EKAM",
    location: "ROWDON STREET",
    tr: "750HP VRV",
    type: "RESIDENTIAL",
    id: "orbit-ekam",
  },
  {
    name: "AUTO MALL",
    location: "RAJARHAT",
    tr: "1000HP VRV",
    type: "MALL",
    id: "auto-mall",
  },
  {
    name: "NCS MALL",
    location: "GUWAHATI",
    tr: "400TR+150TR CHILLER+VRV",
    type: "MALL",
    id: "ncs-mall",
  },
  {
    name: "G-CENTER MALL",
    location: "KOLKATA",
    tr: "600TR CHILLER",
    type: "MALL",
    id: "g-center-mall",
  },

  {
    name: "ITC PUSHPANJALI",
    location: "DURGAPUR",
    tr: "360TR CHILLER",
    type: "HOTELS",
    id: "itc-pushpanjali",
  },
  {
    name: "COURTYARD MARRIOTT",
    location: "SHILLONG",
    tr: "400TR CHILLER",
    type: "HOTELS",
    id: "courtyard-marriott",
  },
  //   {
  //     name: "KIRANSHREE PORTICO",
  //     location: "GUWAHATI",
  //     tr: "0TR CHILLER",
  //     type: "HOTELS",
  //     id: "kiranshree-portico",
  //   },
  {
    name: "PEERLESS INN",
    location: "DHARMATALA",
    tr: "100HP VRV",
    type: "HOTELS",
    id: "peerless-inn",
  },
  {
    name: "AIRPORT CITY HOTEL",
    location: "BIRATI",
    tr: "300HP VRV",
    type: "HOTELS",
    id: "airport-city-hotel",
  },
  {
    name: "JLN MEDICAL COLLEGE",
    location: "BHAGALPUR",
    tr: "1000TR CHILLER",
    type: "HOSPITALS",
    id: "jln-medical-college",
  },
  {
    name: "NARAYAN MEMORIAL HOSPITAL",
    location: "BEHALA",
    tr: "400TR CHILLER",
    type: "HOSPITALS",
    id: "narayan-memorial-hospital",
  },
  {
    name: "DHUBRI MEDICAL COLLEGE",
    location: "ASSAM",
    tr: "1000TR CHILLER",
    type: "HOSPITALS",
    id: "dhubri-medical-college",
  },
  {
    name: "HCG EKO HEALTHCARE",
    location: "NEW TOWN",
    tr: "400TR CHILLER+VRV",
    type: "HOSPITALS",
    id: "hcg-eko-healthcare",
  },
  {
    name: "BANKURA MEDICAL COLLEGE",
    location: "BANKURA",
    tr: "555TR CHILLER",
    type: "HOSPITALS",
    id: "bankura-medical-college",
  },
  {
    name: "NETAJI SUBHAS CANCER INSTITUTE",
    location: "NAYABAD",
    tr: "500TR+220HP CHILLER+VRV",
    type: "HOSPITALS",
    id: "ns-cancer-hospital",
  },
  {
    name: "MEDIASITI",
    location: "SALT LAKE",
    tr: "1500TR CHILLER",
    type: "COMMERCIAL",
    id: "mediasiti",
  },
  {
    name: "KAR BHAVAN",
    location: "GUWAHATI",
    tr: "776HP VRV",
    type: "COMMERCIAL",
    id: "kar-bhawan",
  },
  {
    name: "PS ABACUS",
    location: "NEW TOWN",
    tr: "1500HP VRV",
    type: "COMMERCIAL",
    id: "ps-abacus",
  },
  {
    name: "DIAMOND PRESTIGE",
    location: "AJC BOSE ROAD",
    tr: "1400HP VRV",
    type: "COMMERCIAL",
    id: "diamond-prestige",
  },
  {
    name: "CORPORATE BHAVAN",
    location: "NEW TOWN",
    tr: "700TR CHILLER",
    type: "COMMERCIAL",
    id: "corporate-bhawan",
  },
  {
    name: "BIRLA HIGH SCHOOL",
    location: "MUKUNDAPUR",
    tr: "2000HP VRV",
    type: "SCHOOLS",
    id: "birla-high-school",
  },
  {
    name: "ADAMAS UNIVERSITY",
    location: "BARASAT",
    tr: "450HP VRV",
    type: "SCHOOLS",
    id: "adamas-universty",
  },
  {
    name: "IIT PATNA",
    location: "PATNA",
    tr: "1400HP VRV",
    type: "SCHOOLS",
    id: "iit-patna",
  },
  {
    name: "SOUTH CITY INTERNATIONAL",
    location: "KOLKATA",
    tr: "980HP VRV",
    type: "SCHOOLS",
    id: "south-city-international",
  },
  {
    name: "BD MEMORIAL INSTITUTE",
    location: "KOLKATA",
    tr: "600HP VRV",
    type: "SCHOOLS",
    id: "bd-memorial-institute",
  },
  {
    name: "IIT GUWAHATI",
    location: "GUWAHATI",
    tr: "500HP VRV",
    type: "SCHOOLS",
    id: "iit-guwahati",
  },
  {
    name: "BIHANI ACADEMY",
    location: "JOKA",
    tr: "450HP VRV",
    type: "SCHOOLS",
    id: "bihani-academy",
  },
  {
    name: "PRIYAMVADA BIRLA NURSING INSTITUTE",
    location: "NEW TOWN",
    tr: "240HP VRV",
    type: "SCHOOLS",
    id: "priyamvada-birla",
  },
  {
    name: "INDUS VALLEY WORLD SCHOOL",
    location: "KOLKATA",
    tr: "400HP VRV",
    type: "SCHOOLS",
    id: "indus-valley-world-school",
  },
  {
    name: "RAJIV GANDHI INDOOR STADIUM",
    location: "GUWAHATI",
    tr: "1350TR CHILLER",
    type: "MILESTONE",
    id: "rgis",
  },
  {
    name: "URJA AUDITORIUM",
    location: "PATNA",
    tr: "150TR CHILLER",
    type: "MILESTONE",
    id: "urja",
  },
  //   {
  //     name: "LUX",
  //     location: "JAGDISHPUR",
  //     tr: "00HP VRV",
  //     type: "FACTORY",
  //     id: "lux",
  //   },

  {
    name: "RELIANCE BASIRHAT",
    location: "BASIRHAT",
    tr: "200HP VRV",
    type: "REATAIL",
    id: "reliance-basirhat",
  },
  {
    name: "RELIANCE BARRACPORE",
    location: "BARRACPORE",
    tr: "100HP VRV",
    type: "RETAIL",
    id: "reliance-barrackpore",
  },
  {
    name: "RELIANCE GARIA",
    location: "GARIA",
    tr: "65TR CASSETTE",
    type: "RETAIL",
    id: "reliance-garia",
  },
  {
    name: "YOUSTA COOCHBIHAR",
    location: "COOCHBIHAR",
    tr: "60HP VRV",
    type: "RETAIL",
    id: "yousta-coochbihar",
  },

  {
    name: "UGC DAE BARC OFFICE",
    location: "NEW TOWN",
    tr: "350HP VRV",
    type: "GOVT",
    id: "udbo",
  },
  {
    name: "DIRECTORATE OF REVENUE INTELLIGENCE",
    location: "NEW TOWN",
    tr: "450HP VRV",
    type: "GOVT",
    id: "dorc",
  },
  {
    name: "ESIC HOSPITAL",
    location: "JOKA",
    tr: "1000HP VRV",
    type: "GOVT",
    id: "esic-hospital",
  },
];

export const portfolioTextMilestone = [
  {
    name: "RAJIV GANDHI INDOOR STADIUM",
    location: "GUWAHATI",
    tr: "1350TR CHILLER",
    type: "MILESTONE",
    id: "rgis",
  },
  {
    name: "URJA AUDITORIUM",
    location: "PATNA",
    tr: "150TR CHILLER",
    type: "MILESTONE",
    id: "urja",
  },
  {
    name: "HIGH COURT",
    location: "GUWAHATI",
    tr: "600HP VRV",
    type: "MILESTONE",
    id: "high-court",
  },
  {
    name: "RAJ BHAVAN",
    location: "GUWAHATI",
    tr: "200HP VRV",
    type: "MILESTONE",
    id: "raj-bhavan",
  },
];

export const portfolioTextCurrent = [
  {
    name: "PS NAVYOM",
    location: "NEW ALIPORE",
    tr: "4000HP VRV",
    type: "RESIDENTIAL",
    id: "ps-navyom",
  },
  {
    name: "PS ONE TEN",
    location: "KOLKATA",
    tr: "6000HP VRV",
    type: "RESIDENTIAL",
    id: "ps-one-ten",
  },
  {
    name: "MERLIN 4TH AVENUE",
    location: "MAHISBATHAN",
    tr: "1500HP VRV",
    type: "RESIDENTIAL",
    id: "merlin-4",
  },
  {
    name: "PS ANASSA",
    location: "EM BYPASS",
    tr: "2200HP VRV",
    type: "RESIDENTIAL",
    id: "ps-anassa",
  },
  {
    name: "SIDDHA SKY",
    location: "CANAL ROAD",
    tr: "2500HP VRV",
    type: "RESIDENTIAL",
    id: "siddha-sky",
  },
  {
    name: "TRIVENI MALL",
    location: "SREERMPUR",
    tr: "1650HP VRV",
    type: "MALL",
    id: "  triveni-mall",
  },
  //   {
  //     name: "OZONE PLATINUM MALL",
  //     location: "DHANBAD",
  //     tr: "00TR CHILLER",
  //     type: "MALL",
  //     id: "ozone-platinum-mall",
  //   },
  {
    name: "CRESCENT MALL",
    location: "BURDWAN",
    tr: "400HP VRV",
    type: "MALL",
    id: "crescent-mall",
  },
  {
    name: "PAYEL MALL",
    location: "ASANSOL",
    tr: "600HP VRV",
    type: "MALL",
    id: "payel-mall",
  },
  //   {
  //     name: "SPACE CITY MALL",
  //     location: "SAMBALPUR",
  //     tr: "00TR CHILLER",
  //     type: "MALL",
  //     id: "spcae-city-mall",
  //   },
  {
    name: "BISWANATH MEDICAL COLLEGE",
    location: "ASSAM",
    tr: "1350TR CHILLER",
    type: "HOSPITALS",
    id: "biswanath-medical-college",
  },
  {
    name: "BHARAT SEVASHRAM SANGHA HOSPITAL",
    location: "JOKA",
    tr: "400TR CHILLER",
    type: "HOSPITALS",
    id: "bharat-sevashram",
  },
  {
    name: "SIDDHA ESPLANADE",
    location: "DHARMATALA",
    tr: "1000HP VRV",
    type: "COMMERCIAL",
    id: "siddha-esplanade",
  },
  //   {
  //     name: "SHYAM METALLICS",
  //     location: "TARATALA",
  //     tr: " TR CHILLER",
  //     type: "COMMERCIAL",
  //     id: "shyam-mettalics",
  //   },
  //   {
  //     name: "VIKRAM SOLAR", DOUBLEEEEEEEEEEEE
  //     location: "FALTA",
  //     tr: "TR CHILLER",
  //     type: "COMMERCIAL",
  //     id: "vikram-solar",
  //   },
  {
    name: "HIGH COURT",
    location: "GUWAHATI",
    tr: "600HP VRV",
    type: "MILESTONE",
    id: "high-court",
  },
  {
    name: "RAJ BHAVAN",
    location: "GUWAHATI",
    tr: "200HP VRV",
    type: "MILESTONE",
    id: "raj-bhavan",
  },
  //   {
  //     name: "AMUL",
  //     location: "",
  //     tr: "00HP VRV",
  //     type: "FACTORY",
  //     id: "amul",
  //   },
  //   {
  //     name: "SABYASACHI",
  //     location: "ACTIVE CARE",
  //     tr: "00HP VRV",
  //     type: "FACTORY",
  //     id: "sabyasachi",
  //   },
  //   {
  //     name: "VIKRAM SOLAR",      DOUBLEEEEEEEEEEEE
  //     location: "FALTA",
  //     tr: "00HP VRV",
  //     type: "FACTORY",
  //     id: "vikram-solar",
  //   },
  //   {
  //     name: "MODI HOUSE",
  //     location: "NEW TOWN",
  //     tr: "00HP VRV",
  //     type: "BUNGALOW",
  //     id: "modi-house",
  //   },
  //   {
  //     name: "TODI HOUSE",
  //     location: "PENN ROAD",
  //     tr: "00HP VRV",
  //     type: "BUNGALOW",
  //     id: "todi-house",
  //   },
  //   {
  //     name: "GOENKA HOUSE",
  //     location: "BELVEDERE ROAD",
  //     tr: "00HP VRV",
  //     type: "BUNGALOW",
  //     id: "goenka-house",
  //   },
  //   {
  //     name: "GREENPLY RESIDENCE",
  //     location: "ASHOKA ROAD",
  //     tr: "00HP VRV",
  //     type: "BUNGALOW",
  //     id: "greenply-residence",
  //   },
  //   {
  //     name: "ALCOVE HOUSE",
  //     location: "HARISH MUKHERJEE RD",
  //     tr: "00HP VRV",
  //     type: "BUNGALOW",
  //     id: "alcove-house",
  //   },
  {
    name: "PDCA",
    location: "RANCHI",
    tr: "350HP VRV",
    type: "GOVT",
    id: "pdca",
  },
];
