export const portfolioTextCard = [
  {
    name: "MERLIN 5TH AVENUE",
    location: "MAHISBATHAN",
    tr: "2200HP VRV",
    type: "RESIDENTIAL",
    id: "merlin-5",
  },
  {
    name: "ORBIT SKYGARDEN",
    location: "KOLKATA",
    tr: "450HP VRV",
    type: "RESIDENTIAL",
    id: "orbit-skygarden",
  },
  {
    name: "AVIDIPTA PHASE-II",
    location: "MUKUNDAPUR",
    tr: "1000HP VRV",
    type: "RESIDENTIAL",
    id: "avidipta-p2",
  },
  {
    name: "ORBIT EKAM",
    location: "ROWDON STREET",
    tr: "750HP VRV",
    type: "RESIDENTIAL",
    id: "orbit-ekam",
  },
  {
    name: "PAYEL MALL",
    location: "ASANSOL",
    tr: "600HP VRV",
    type: "MALL",
    id: "payel-mall",
  },
  {
    name: "AUTO MALL",
    location: "RAJARHAT",
    tr: "1000HP VRV",
    type: "MALL",
    id: "auto-mall",
  },
  {
    name: "NCS MALL",
    location: "GUWAHATI",
    tr: "400TR CHILLER & 150HPVRV",
    type: "MALL",
    id: "ncs-mall",
  },
  {
    name: "G-CENTER MALL",
    location: "KOLKATA",
    tr: "600TR CHILLER",
    type: "MALL",
    id: "g-center-mall",
  },
  {
    name: "DIAMOND PLAZA",
    location: "NAGERBAZAR",
    tr: "1200TR CHILLER",
    type: "MALL",
    id: "diamond-plaza",
  },
  {
    name: "QUEST MALL FOOD COURT",
    location: "KOLKATA",
    tr: "VENTILATION AND AC",
    type: "MALL",
    id: "quest-mall",
  },

  {
    name: "ITC PUSHPANJALI",
    location: "DURGAPUR",
    tr: "360TR CHILLER",
    type: "HOTELS",
    id: "itc-pushpanjali",
  },
  {
    name: "COURTYARD MARRIOTT",
    location: "SHILLONG",
    tr: "400TR CHILLER",
    type: "HOTELS",
    id: "courtyard-marriott",
  },
  {
    name: "VISHWARATNA HOTEL",
    location: "GUWAHATI",
    tr: "300TR CHILLER",
    type: "HOTELS",
    id: "vishwaratna-hotel",
  },
  {
    name: "GARGEE GRAND",
    location: "PATNA",
    tr: "250HP VRV",
    type: "HOTELS",
    id: "gargi-grand",
  },
  {
    name: "ATITHI HOTEL",
    location: "GUWAHATI",
    tr: "250HP VRV",
    type: "HOTELS",
    id: "atithi-hotel",
  },
  {
    name: "KIRANSHREE PORTICO",
    location: "GUWAHATI",
    tr: "390TR CHILLER & 124HP VRV",
    type: "HOTELS",
    id: "kiranshree-portico",
  },
  {
    name: "PEERLESS INN",
    location: "DHARMATALA",
    tr: "118HP VRV",
    type: "HOTELS",
    id: "peerless-inn",
  },
  {
    name: "AIRPORT CITY HOTEL",
    location: "BIRATI",
    tr: "300HP VRV",
    type: "HOTELS",
    id: "airport-city-hotel",
  },

  {
    name: "BELLE VUE CLINIC",
    location: "MINTO PARK",
    tr: "100HP VRV",
    type: "HOSPITALS",
    id: "belle-vue-clinic",
  },
  {
    name: "CORAS HOSPITAL",
    location: "GUWAHATI",
    tr: "500TR CHILLER",
    type: "HOSPITALS",
    id: "coras-hospital",
  },
  {
    name: "JLN MEDICAL COLLEGE",
    location: "BHAGALPUR",
    tr: "1000TR CHILLER",
    type: "HOSPITALS",
    id: "jln-medical-college",
  },
  {
    name: "NARAYAN MEMORIAL HOSPITAL",
    location: "BEHALA",
    tr: "400TR CHILLER",
    type: "HOSPITALS",
    id: "narayan-memorial-hospital",
  },
  {
    name: "DHUBRI MEDICAL COLLEGE",
    location: "ASSAM",
    tr: "1150TR CHILLER",
    type: "HOSPITALS",
    id: "dhubri-medical-college",
  },
  {
    name: "HCG EKO HEALTHCARE",
    location: "NEW TOWN",
    tr: "400TR CHILLER+VRV",
    type: "HOSPITALS",
    id: "hcg-eko-healthcare",
  },
  {
    name: "BANKURA MEDICAL COLLEGE",
    location: "BANKURA",
    tr: "555TR CHILLER",
    type: "HOSPITALS",
    id: "bankura-medical-college",
  },
  {
    name: "NETAJI SUBHAS CANCER INSTITUTE",
    location: "NAYABAD",
    tr: "500TR CHILLER & 220HP VRV",
    type: "HOSPITALS",
    id: "ns-cancer-hospital",
  },

  {
    name: "MEDIASITI",
    location: "SALT LAKE",
    tr: "1500TR CHILLER",
    type: "COMMERCIAL",
    id: "mediasiti",
  },
  {
    name: "KAR BHAVAN",
    location: "GUWAHATI",
    tr: "864HP VRV",
    type: "COMMERCIAL",
    id: "kar-bhavan",
  },
  {
    name: "PS ABACUS",
    location: "NEW TOWN",
    tr: "1500HP VRV",
    type: "COMMERCIAL",
    id: "ps-abacus",
  },
  {
    name: "DIAMOND PRESTIGE",
    location: "AJC BOSE ROAD",
    tr: "1400HP VRV",
    type: "COMMERCIAL",
    id: "diamond-prestige",
  },
  {
    name: "CORPORATE BHAVAN",
    location: "NEW TOWN",
    tr: "700TR CHILLER",
    type: "COMMERCIAL",
    id: "corporate-bhawan",
  },

  {
    name: "BIRLA HIGH SCHOOL",
    location: "MUKUNDAPUR",
    tr: "2000HP VRV",
    type: "SCHOOLS",
    id: "birla-high-school",
  },
  {
    name: "ADAMAS UNIVERSITY",
    location: "BARASAT",
    tr: "450HP VRV",
    type: "SCHOOLS",
    id: "adamas-university",
  },
  {
    name: "IIT PATNA",
    location: "PATNA",
    tr: "1400HP VRV",
    type: "SCHOOLS",
    id: "iit-patna",
  },
  {
    name: "SOUTH CITY INTERNATIONAL",
    location: "KOLKATA",
    tr: "980HP VRV",
    type: "SCHOOLS",
    id: "south-city-international",
  },
  {
    name: "BD MEMORIAL INSTITUTE",
    location: "KOLKATA",
    tr: "600HP VRV",
    type: "SCHOOLS",
    id: "bd-memorial-institute",
  },
  // {
  //   name: "BIHANI ACADEMY",
  //   location: "JOKA",
  //   tr: "450HP VRV",
  //   type: "SCHOOLS",
  //   id: "bihani-academy",
  // },
  {
    name: "PRIYAMVADA BIRLA NURSING INSTITUTE",
    location: "NEW TOWN",
    tr: "240HP VRV",
    type: "SCHOOLS",
    id: "priyamvada-birla",
  },
  {
    name: "INDUS VALLEY WORLD SCHOOL",
    location: "KOLKATA",
    tr: "400HP VRV",
    type: "SCHOOLS",
    id: "indus-valley-world-school",
  },
  {
    name: "ROYAL GROUP OF INSTITUTION",
    location: "GUWAHATI",
    tr: "2000TR CHILLER + VRV",
    type: "SCHOOLS",
    id: "royal-group-of-institution",
  },
  {
    name: "KAZIRANGA UNIVERSITY",
    location: "JORHAT",
    tr: "500TR CHILLER",
    type: "SCHOOLS",
    id: "kaziranga-university",
  },

  {
    name: "RAJIV GANDHI INDOOR STADIUM",
    location: "GUWAHATI",
    tr: "1150TR CHILLER",
    type: "MILESTONE",
    id: "rgis",
  },
  {
    name: "URJA AUDITORIUM",
    location: "PATNA",
    tr: "300TR CHILLER",
    type: "MILESTONE",
    id: "urja",
  },

  //   {
  //     name: "LUX",
  //     location: "JAGDISHPUR",
  //     tr: "00HP VRV",
  //     type: "INDUSTRIAL",
  //     id: "lux",
  //   },

  // {
  //   name: "RELIANCE BASIRHAT",
  //   location: "BASIRHAT",
  //   tr: "178HP VRV",
  //   type: "RETAIL",
  //   id: "reliance-basirhat",
  // },
  // {
  //   name: "RELIANCE BARRACPORE",
  //   location: "BARRACPORE",
  //   tr: "90HP VRV",
  //   type: "RETAIL",
  //   id: "reliance-barrackpore",
  // },
  // {
  //   name: "RELIANCE GARIA",
  //   location: "GARIA",
  //   tr: "73TR CASSETTE",
  //   type: "RETAIL",
  //   id: "reliance-garia",
  // },
  // {
  //   name: "YOUSTA COOCHBIHAR",
  //   location: "COOCHBIHAR",
  //   tr: "60HP VRV",
  //   type: "RETAIL",
  //   id: "yousta-coochbihar",
  // },

  {
    name: "UGC DAE BARC OFFICE",
    location: "NEW TOWN",
    tr: "350HP VRV",
    type: "GOVT",
    id: "udbo",
  },
  {
    name: "AUDIT BHAVAN",
    location: "RANCHI",
    tr: "350HP VRV",
    type: "GOVT",
    id: "audit-bhavan",
  },
  {
    name: "DIRECTORATE OF REVENUE INTELLIGENCE",
    location: "NEW TOWN",
    tr: "450HP VRV",
    type: "GOVT",
    id: "dorc",
  },
  {
    name: "ESIC HOSPITAL",
    location: "JOKA",
    tr: "1000HP VRV",
    type: "GOVT",
    id: "esic-hospital",
  },
];

export const portfolioTextMilestone = [
  {
    name: "RAJIV GANDHI INDOOR STADIUM",
    location: "GUWAHATI",
    tr: "1150TR CHILLER",
    type: "MILESTONE",
    id: "rgis",
  },
  {
    name: "DHUBRI MEDICAL COLLEGE",
    location: "ASSAM",
    tr: "1150TR CHILLER",
    type: "HOSPITALS",
    id: "dhubri-medical-college",
  },
  {
    name: "URJA AUDITORIUM",
    location: "PATNA",
    tr: "300TR CHILLER",
    type: "MILESTONE",
    id: "urja",
  },
  {
    name: "MEDIASITI",
    location: "SALT LAKE",
    tr: "1500TR CHILLER",
    type: "COMMERCIAL",
    id: "mediasiti",
  },
  {
    name: "PS ONE TEN",
    location: "KOLKATA",
    tr: "6000HP VRV",
    type: "RESIDENTIAL",
    id: "ps-one-ten",
  },
  {
    name: "HIGH COURT",
    location: "ITANAGAR",
    tr: "800HP VRV",
    type: "MILESTONE",
    id: "high-court",
  },
  // {
  //   name: "RAJ BHAVAN",
  //   location: "GUWAHATI",
  //   tr: "200HP VRV",
  //   type: "MILESTONE",
  //   id: "raj-bhavan",
  // },
];

export const portfolioTextCurrent = [
  {
    name: "PS NAVYOM",
    location: "NEW ALIPORE",
    tr: "4000HP VRV",
    type: "RESIDENTIAL",
    id: "ps-navyom",
  },
  {
    name: "PS ONE TEN",
    location: "KOLKATA",
    tr: "6000HP VRV",
    type: "RESIDENTIAL",
    id: "ps-one-ten",
  },
  {
    name: "MERLIN ELEMENTS",
    location: "KOLKATA",
    tr: "1100HP VRV",
    type: "RESIDENTIAL",
    id: "merlin-elements",
  },
  {
    name: "MERLIN 4TH AVENUE",
    location: "MAHISBATHAN",
    tr: "1500HP VRV",
    type: "RESIDENTIAL",
    id: "merlin-4",
  },
  {
    name: "PS ANASSA",
    location: "EM BYPASS",
    tr: "2200HP VRV",
    type: "RESIDENTIAL",
    id: "ps-anassa",
  },
  {
    name: "SIDDHA SKY",
    location: "CANAL ROAD",
    tr: "2585HP VRV",
    type: "RESIDENTIAL",
    id: "siddha-sky",
  },
  {
    name: "ORBIT VICTORIA",
    location: "KOLKATA",
    tr: "624HP VRV",
    type: "RESIDENTIAL",
    id: "orbit-victoria",
  },

  {
    name: "IIT GUWAHATI",
    location: "GUWAHATI",
    tr: "500HP VRV",
    type: "SCHOOLS",
    id: "iit-guwahati",
  },

  {
    name: "TRIVENI MALL",
    location: "SREERAMPUR",
    tr: "1600HP VRV & VENTILATION",
    type: "MALL",
    id: "triveni-mall",
  },
  {
    name: "OZONE PLATINUM MALL",
    location: "DHANBAD",
    tr: "1000TR CHILLER",
    type: "MALL",
    id: "ozone-platinum-mall",
  },
  {
    name: "CRESCENT MALL",
    location: "BURDWAN",
    tr: "400HP VRV",
    type: "MALL",
    id: "crescent-mall",
  },
  {
    name: "SPACE CITY MALL",
    location: "SAMBALPUR",
    tr: "500TR CHILLER",
    type: "MALL",
    id: "space-city-mall",
  },

  {
    name: "MOREGAON MEDICAL COLLEGE",
    location: "MOREGAON",
    tr: "710HP VRV",
    type: "HOSPITALS",
    id: "moregaon-medical-college",
  },
  {
    name: "BHAGIRATHI NEOTIA HOSPITAL",
    location: "GUWAHATI",
    tr: "360TR CHILLER",
    type: "HOSPITALS",
    id: "bhagirathi-neotia-hospital",
  },
  {
    name: "TAMALPUR MEDICAL COLLEGE",
    location: "TAMALPUR",
    tr: "710HP VRV",
    type: "HOSPITALS",
    id: "tamalpur-medical-college",
  },
  {
    name: "BISWANATH MEDICAL COLLEGE",
    location: "ASSAM",
    tr: "1300TR CHILLER",
    type: "HOSPITALS",
    id: "biswanath-medical-college",
  },
  {
    name: "BHARAT SEVASHRAM SANGHA HOSPITAL",
    location: "JOKA",
    tr: "400TR CHILLER",
    type: "HOSPITALS",
    id: "bharat-sevashram",
  },

  {
    name: "PRIMARC CHAMBER",
    location: "KOLKATA",
    tr: "950HP VRV",
    type: "COMMERCIAL",
    id: "primarc-chamber",
  },
  {
    name: "BERGER HOUSE",
    location: "KOLKATA",
    tr: "",
    type: "COMMERCIAL",
    id: "berger-house",
  },
  {
    name: "SIDDHA ESPLANADE",
    location: "DHARMATALA",
    tr: "360HP VRV",
    type: "COMMERCIAL",
    id: "siddha-esplanade",
  },
  {
    name: "SHYAM METALLICS",
    location: "TARATALA",
    tr: "450TR CHILLER",
    type: "COMMERCIAL",
    id: "shyam-mettalics",
  },

  {
    name: "HIGH COURT",
    location: "ITANAGAR",
    tr: "800HP VRV",
    type: "MILESTONE",
    id: "high-court",
  },
  // {
  //   name: "RAJ BHAVAN",
  //   location: "GUWAHATI",
  //   tr: "200HP VRV",
  //   type: "MILESTONE",
  //   id: "raj-bhavan",
  // },
  // {
  //   name: "AMUL",
  //   location: "JAGDISHPUR",
  //   tr: "70HP VRV",
  //   type: "INDUSTRIAL",
  //   id: "amul",
  // },
  {
    name: "SABYASACHI CALCUTTA LLP",
    location: "ACTIVE ACRES",
    tr: "526HP VRV",
    type: "INDUSTRIAL",
    id: "sabyasachi",
  },
  {
    name: "VIKRAM SOLAR",
    location: "FALTA",
    tr: "250TR CHILLER",
    type: "INDUSTRIAL",
    id: "vikram-solar",
  },
];
